### ISSUE TITLE
generate grammar from parser

### ISSUE THREAD

**Issue by fponticelli** [deathbeam/parsihax#3]
Not sure how feasible this could be but it would be amazing if you could use the parser to generate a human readable text that describes the parsing rules.

**Comment by deathbeam** [comment]
I am not really sure what do you mean 😄 If you mean to implement something that will show entire parser chain from specified parser and show it in some readable form, then I think that will be not possible to do without changing current implementation of parsers, and that is that they know only about previous parser on what are they chained, and that is all. There is one exception where they know about multiple errors when there are multiple possible ways that parsing can continue, and none of them succeeds. I think displaying parsing rules in human readable text can be done in similar way that I am doing it currently with errors, but it will affect parser performance.

**Comment by fponticelli** [comment]
Got it ... I thought that it might be the case ... anyway something maybe to keep in mind for newer versions ;)
