### ISSUE TITLE
parsihax haxelib release 2.0.1 contains empty src folder

### ISSUE THREAD

**Issue by andyli** [deathbeam/parsihax#5]
As seen in https://lib.haxe.org/p/parsihax/2.0.1/files, the src folder is empty.
The releasenote in haxelib.json wasn't updated too.

**Comment by deathbeam** [comment]
Oh, oops, I haven't used haxelib in a while my bad. Fixed in https://github.com/deathbeam/parsihax/commit/38bbf3082fa5c00cbad073efe8b155d952784251
